on:
  push:
    branches:
      - staging

name: Deploy to Staging
jobs:
  sonarcloud-flask:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: ./flask-api-ml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  sonarcloud-streamlit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: ./streamlit_app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test-docker-compose:
    needs: [sonarcloud-flask, sonarcloud-streamlit]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up -d
      - name: Shutdown Docker Compose
        run: docker-compose down

  create-pull-request:
    needs: test-docker-compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: staging
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Merge staging into main"
          branch: merge-staging-to-main-${{ github.run_number }}
          title: "Merge staging into main"
          body: "This pull request is auto-generated by GitHub Actions."
          base: main
          labels: |
            automated pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}