name: CI/CD Pipeline for Developpment

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.18'
    - name: Install dependencies
      working-directory: ./flask-api-ml/model
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      working-directory: ./flask-api-ml/model
      run: |
        # Replace with your test command
        pytest tests/*

  push-to-staging:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: staging

      - name: Pull Request Branch Merge
        run: |
          git fetch origin ${{ github.head_ref }}
          git merge --no-ff origin/${{ github.head_ref }}

      - name: Push to Staging
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging

