name: CI/CD Pipeline for Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  test:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Compose Services
        run: docker-compose build

  build-and-push:
    if: ${{ github.event_name == 'push' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker-compose build
          docker-compose push

  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull and Run Docker Images
        run: |
          docker-compose pull
          docker-compose up -d