name: CI/CD Pipeline for Developpment

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.18'
    - name: Install dependencies
      working-directory: ./flask-api-ml/model
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      working-directory: ./flask-api-ml/model
      run: |
        # Replace with your test command
        pytest tests/*

  push-to-staging:
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge dev -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: staging
          message: Merge dev into staging - gitAction[BOT]
          github_token: ${{ secrets.GIT_TOKEN }}

